### ISSUE TITLE
initial load time slider issue

### ISSUE THREAD

**Issue by ashishkraff** [gilbox/kinetic-slider#1]
Hello,

i am currently having an issue for rendering images into slider, my slider is not taking full width but when i resize window then automatically it takes the appropriate width according to screen. here is my link http://bigdatacsx.com/#/ . i have multiple sliders in this screen , so when i do inspect element or resize the window then only the slider is getting displayed properly else only one image is displaying can you please help me out with this.
## 

thanks,
Ashish

**Comment by gilbox** [comment]
Your link asks for username/password

**Comment by ashishkraff** [comment]
hello,
username : bigdata
password : pvr

## 

thanks,
ashish

**Comment by gilbox** [comment]
I was able to fix the problem directly on your page by adding `setTimeout(onWinResize,0);` to the end of the link function. I'm not sure if this is really a bug or your setup is incorrect. 

However, if it is a bug I have no plan to fix it as I'm not currently supporting this project. If you'd like to use a slider that's being actively developed please try [infinite-slider](https://github.com/gilbox/kinetic-slider). It's being used in a couple of high-profile websites and undergoes a lot of testing and I will fix any bugs that you find with it.

**Comment by ashishkraff** [comment]
Hello Gil,

Thanks for your support i will revert back to you in case of any trouble.

## 

Regards,
Ashish
